---
title: "PM2.5"
output:
  html_document: default
  pdf_document: default
  word_document: default
Binome: LIU HAO,  Scochivin
---

```{r data processing unit}
#####################################
#Beijing PM2.5 Data Data Set 
#Data Set Information:
#The date time period is between Jan 1st, 2010 to Dec 31st, 2014


#Initialize environment
rm(list=ls())
graphics.off()

#Read data set
dataset = read.csv("PRSA_data_2010.1.1-2014.12.31.csv",sep = ",",header = TRUE)
#Print orignal dimension
dim(dataset)
#Remove index column 
dataset = dataset[,2:ncol(dataset)]
dim(dataset)
Y = dataset[,'pm2.5']
length(Y)
Y = Y[1:length(Y)-1]
length(Y)
dataset = dataset[2:nrow(dataset),]
dim(dataset)

dataset = cbind(dataset,Y)

day_of_year <- function(year,month,day)
{
  if(year%%4!=0){
    if(month==1)
      dayofyear = day
    if(month==2)
      dayofyear = 31+day
    if(month==3)
      dayofyear = 31+28+day
    if(month==4)
      dayofyear = 31+28+31+day
    if(month==5)
      dayofyear = 31+28+31+30+day
    if(month==6)
      dayofyear = 31+28+31+30+31+day
    if(month==7)
      dayofyear = 31+28+31+30+31+30+day
    if(month==8)
      dayofyear = 31+28+31+30+31+30+31+day
    if(month==9)
      dayofyear = 31+28+31+30+31+30+31+31+day
    if(month==10)
      dayofyear = 31+28+31+30+31+30+31+31+30+day
    if(month==11)
      dayofyear = 31+28+31+30+31+30+31+31+30+31+day
    if(month==12)
      dayofyear = 31+28+31+30+31+30+31+31+30+31+30+day
  }
  if(year%%4==0){
    if(month==1)
      dayofyear = day
    if(month==2)
      dayofyear = 31+day
    if(month==3)
      dayofyear = 31+29+day
    if(month==4)
      dayofyear = 31+29+31+day
    if(month==5)
      dayofyear = 31+29+31+30+day
    if(month==6)
      dayofyear = 31+29+31+30+31+day
    if(month==7)
      dayofyear = 31+29+31+30+31+30+day
    if(month==8)
      dayofyear = 31+29+31+30+31+30+31+day
    if(month==9)
      dayofyear = 31+29+31+30+31+30+31+31+day
    if(month==10)
      dayofyear = 31+29+31+30+31+30+31+31+30+day
    if(month==11)
      dayofyear = 31+29+31+30+31+30+31+31+30+31+day
    if(month==12)
      dayofyear = 31+29+31+30+31+30+31+31+30+31+30+day
  }
  return(dayofyear)
}


day = 0
for (i in c(1:nrow(dataset)))
{
  day[i] = day_of_year(dataset[i,1],dataset[i,2],dataset[i,3])
}
dataset[,'day'] = day 

day  = dataset[,'day']
month = dataset[,'month']
hour = dataset[,'hour'] 

sin_month = sin(month*2*pi/12)
cos_month = cos(month*2*pi/12)

sin_day = 0
cos_day = 0
for (i in c(1:nrow(dataset)))
{
  if(dataset[i,'year']%%4!=0)
  {
    sin_day[i] = sin(day[i]*2*pi/365)
    cos_day[i] = cos(day[i]*2*pi/365)
  }
  if(dataset[i,'year']%%4==0)
  {
    sin_day[i] = sin(day[i]*2*pi/366)
    cos_day[i] = cos(day[i]*2*pi/366)
  }
}
sin_hour = sin(hour*2*pi/24)
cos_hour = cos(hour*2*pi/24)


dataset[,'month'] <- NULL
dataset[,'day'] <- NULL
dataset[,'hour'] <- NULL
dataset = cbind(dataset,sin_month,cos_month,sin_day,cos_day,sin_hour,cos_hour)



#Remove NA data from dataset
dataset = na.omit(dataset)
#Check demision again
dim(dataset)
#Check dataset
head(dataset)
#dummy codage
library(dummies)
cbwd = dummy(dataset[,'cbwd'])
dataset = cbind(dataset,cbwd)
#remove cbwd column
dataset[,'cbwd'] <- NULL
#Plot histogram
dim(dataset)

summary(dataset)
```

```{r pressure, echo=FALSE}
#take 8000 sample randomly from orginal dataset and getnerate a subset
n = 10
sample = sample(c(1:nrow(dataset)),n)
subset = dataset[sample,]

#PLot to see variables' distrubution
# Density plot
colnames <- dimnames(subset)[[2]]
for (i in 1:18) {
  d <- density(unlist(subset[i]))
  plot(d, type="n", main=colnames[i])
  polygon(d, col="grey", border="blue")
}
summary(subset)
```

```{r}
#Plot correlation matrix
library(corrplot)
correlation = cor(subset)
par(mfrow=c(1,1))
corrplot(correlation, method="circle")
#We can see quite strong correlations between many varaibles
# sin_day & sin_month
# cos_day & cos_month
# cos_day & DEWP
# cos_day & TEMP  etc.
```

```{r}
colnames <- dimnames(subset)[[2]]
for (i in c(1:ncol(dataset)))
{ 
  boxplot(dataset[,i])
}
```

```{r seperation data into training and test sets  80% / 20%}
# Seperation subset into X and Y
Y = subset[,'pm2.5']
# scale(X) Normalization input
X = subset[,-2]

library(matrixStats)
sdX = colSds(as.matrix(X)) ;meanX = colMeans(X); X = scale(X)
#(train_X - mean(train_X)) / sd(train_X)
#(test_X - mean(train_X)) / sd(train_X)
# Seperation to training and test sets
training_size = 0.8*nrow(subset)
train_Y = Y[1:training_size]
train_X = X[1:training_size,]
test_Y = Y[(training_size+1):nrow(subset)]
test_X = X[(training_size+1):nrow(subset),]
```

```{r}
#Linear regression
reg = lm('train_Y~.', data = as.data.frame(cbind(train_X,train_Y)))
summary(reg)
```


```{r}
#### model selection
regbackward = step(reg,direction = 'backward'); 
summary(regbackward)
regforward = step(lm(train_Y~1,data = as.data.frame(cbind(train_X,train_Y))),list(upper=reg),direction = 'forward'); 
summary(regforward)

extractAIC(regbackward,k=log(n))
extractAIC(regforward,k=log(n))

formula(regbackward)
sum((train_Y-regbackward$fitted.values)^2)/training_size
formula(regforward)
sum((train_Y-regforward$fitted.values)^2)/training_size
```

```{r}
plot(train_Y, regbackward$residuals)
abline(a = 0,b =0, col="red")
plot(train_Y, regbackward$fitted.values)
abline(a = 0,b =1, col="red")
sum((train_Y-regbackward$fitted.values)^2)/training_size
```


```{r}
library(MASS)
reg_l2 = lm.ridge('pm2.5~.', data = as.data.frame(subset), lambda = seq(10,11,0.001))
#coef(reg_l2)
plot(reg_l2$GCV,pch=16,type='b',col='blue')
plot(reg_l2)
summary(reg_l2)
cf = sort(coef(reg_l2),decreasing = TRUE)
cf[1:5]
attributes(reg_l2)
# select function to select best cross validation
select(reg_l2)
GCV.MIN<-reg_l2$GCV[which.min(reg_l2$GCV)]
reg_l2 = lm.ridge('pm2.5~.', data = as.data.frame(subset), lambda = as.numeric(names(GCV.MIN)))
plot(reg_l2)
summary(reg_l2)
predicted =  as.matrix(cbind(const=1,train_X))%*%as.vector(coef(reg_l2))
sum((train_Y-predicted)^2)/training_size
```

```{r}
library(lars)
reg_l1 = lars(as.matrix(train_X),as.matrix(train_Y),type="lasso")
par(mfrow=c(2,1))
plot(reg_l1)
plot(c(reg_l1$lambda,0),pch=16,type='b',col='blue'); grid()

print(coef(reg_l1))
#When the mode is lambda then the s is the lambda value
coef = predict.lars(reg_l1, train_X, type='coefficients',mode='lambda',s=0.4)
coefl1 = coef$coefficients
#par(mforw=c(1,1));
barplot(coefl1, main = 'lasso, l=1', col = 'blue')


coef.2 = predict.lars(reg_l1, train_X, type='coefficients',mode='lambda',s=1000)
#print(coef.2$coefficients)
#print(coef.4)
#print(coef.6)
count = 0;
for (i in c(1:18))
{
  if (!is.na(coef.2$coefficients[i]))
  {
    if (coef.2$coefficients[i]!=0)
    {
      count = count+1;
      print(coef.2$coefficients[i]);
    }
  }
}
print(count);
length(coef.2$coefficients)


## For l1 regularization
fitted = predict.lars(reg_l1, train_X, type='fit',mode='lambda',s=1)
# Mean Square Error
sum((train_Y-fitted$fit)^2)/training_size
```

